[workspace]
pr_name = "Release {{ package }} v{{ version }}"
git_tag_enable = false
git_release_enable = false

[[package]]
name = "comfyui-client"
git_tag_name = "v{{ version }}"
git_tag_enable = true
git_release_enable = true

